User registration email not validated #720
simplcommerce/SimplCommerce pull request #1068
Opened 2024-01-04 13:50 UTC by SatyaSandeep51

User after registering with an Email gets the verification link to his Mailbox. By clicking on the verification link he/she will be redirected to the verifying page and from there user can go to login after the successful verification. Used a sample email and app specific password to generate emails to the registered user. 
Email Id : sampleemail304@gmail.com
Password : Welcome@123
App Specific Password : mecv erfk mosu fvji 

Modified Files :
-- src/Modules/SimplCommerce.Module.Core/Areas/Core/Controllers/AccountController.cs
-- src/Modules/SimplCommerce.Module.EmailSenderSmtp/EmailSender.cs

2024-01-19 12:23 UTC, hishamco commented
Please resolve the conflicts

2024-01-29 23:53 UTC, afernandes commented on src/Modules/SimplCommerce.Module.EmailSenderSmtp/EmailSender.cs
> +            _emailConfig.SmtpUsername = "sampleemail304@gmail.com";
It is not recommended to use a fixed email.
The email must be configurable.

2024-01-29 23:55 UTC, afernandes requested changes
Review changed settings

2024-01-29 23:55 UTC, afernandes commented on src/SimplCommerce.WebHost/appsettings.json
> +    "DefaultConnection": "server=DotNetFSD\\SQLEXPRESS;database = SimplCommerce;user id = sa; password = pass@123;trustservercertificate = true;MultipleActiveResultSets=true"
???

2024-01-30 15:53 UTC, hishamco commented
Closed while there's no respond from the author

Feel free to reopen the PR again

2024-01-30 15:54 UTC, closed without merging