added tests for SimplCommerce.Module.Core - WidgetInstanceService
simplcommerce/SimplCommerce pull request #1077
Opened 2024-01-10 06:04 UTC by Arunkumar0610

added tests for #1037 #1069 
**SimplCommerce.Module.Core ->Services ->WidgetInstanceService**

2024-01-10 20:47 UTC, hishamco requested changes

2024-01-10 20:47 UTC, hishamco commented on test/SimplCommerce.Module.Core.Tests/Services/WidgetInstanceServiceTests.cs
> +        #region PositiveTestCases
Remove the region

2024-01-10 20:47 UTC, hishamco commented on test/SimplCommerce.Module.Core.Tests/Services/WidgetInstanceServiceTests.cs
> +            new WidgetInstance { PublishStart = DateTimeOffset.Now.AddDays(-1), PublishEnd = DateTimeOffset.Now.AddDays(1) },
Format

2024-01-10 20:47 UTC, hishamco commented on test/SimplCommerce.Module.Core.Tests/Services/WidgetInstanceServiceTests.cs
> +        #region NegativeTestCases
Remove

2024-01-10 20:47 UTC, hishamco commented on test/SimplCommerce.Module.Core.Tests/Services/WidgetInstanceServiceTests.cs
> +            new WidgetInstance { PublishStart = DateTimeOffset.Now.AddDays(1), PublishEnd = DateTimeOffset.Now.AddDays(2) },
Format

2024-01-11 06:19 UTC, hishamco requested changes

2024-01-11 06:19 UTC, hishamco commented on test/SimplCommerce.Module.Core.Tests/SimplCommerce.Module.Core.Tests.csproj
> +
```suggestion
```

2024-01-11 06:19 UTC, hishamco commented
Confirm that everything works as expected

2024-01-11 08:50 UTC, Arunkumar0610 commented
Yes this PR working as excepted

2024-01-11 10:36 UTC, merged