added unit tests pricing module controllers
simplcommerce/SimplCommerce pull request #1078
Opened 2024-01-10 06:16 UTC by Arunkumar0610

added tests for #1037 #1069 
**SimplCommerce.Module.Pricing->Controllers - >CartRuleApiController & CartRuleUsageApiController**

2024-01-10 20:46 UTC, hishamco requested changes
Please format and remove white spaces

2024-01-10 20:46 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +            // Act
```suggestion

            // Act
```

2024-01-10 20:46 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +            // Assert
```suggestion

            // Assert
```

2024-01-10 20:46 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +
```suggestion
```

2024-01-10 20:46 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +            // Act
```suggestion

            // Act
```

2024-01-10 20:46 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +            // Assert
```suggestion

            // Assert
```

2024-01-10 20:46 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +
```suggestion
```

2024-01-11 06:14 UTC, hishamco requested changes

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +            // Act
```suggestion
            // Act
```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +            // Act
```suggestion
            // Act
```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleUsageApiControllerTests.cs
> +        [Fact]
```suggestion
        [Fact]
```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleUsageApiControllerTests.cs
> +        public class Itemsobject
```suggestion

        public class Itemsobject
```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleUsageApiControllerTests.cs
> +        public class searchObject
```suggestion

        public class searchObject
```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleUsageApiControllerTests.cs
> +            public List<Itemsobject> Items { get; set; }
```suggestion
            public List<Itemsobject> Items { get; set; }

```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleUsageApiControllerTests.cs
> +            public int NumberOfPages { get; set; }
```suggestion
            public int NumberOfPages { get; set; }

```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleUsageApiControllerTests.cs
> +
```suggestion
```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleUsageApiControllerTests.cs
> +    }
```suggestion
    }
```

2024-01-11 06:14 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/SimplCommerce.Module.Pricing.Tests.csproj
> +
```suggestion
```

2024-01-11 06:17 UTC, hishamco requested changes

2024-01-11 06:17 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleApiControllerTests.cs
> +namespace SimplCommerce.Module.Pricing.Tests.Controllers
```suggestion

namespace SimplCommerce.Module.Pricing.Tests.Controllers
```

2024-01-11 06:17 UTC, hishamco commented on test/SimplCommerce.Module.Pricing.Tests/Controllers/CartRuleUsageApiControllerTests.cs
> +        }
```suggestion
        }
```

2024-01-11 06:18 UTC, hishamco commented
@Arunkumar0610 please run the tests at your end and make sure everything works as expected

2024-01-11 08:55 UTC, Arunkumar0610 commented
@hishamco Yes I ran the tests at my end everything works as excepted

2024-01-11 10:36 UTC, merged

2024-01-11 13:00 UTC, Arunkumar0610 commented
@hishamco resolved the conflict and its merged successfully