added unit tests for productcomparison module
simplcommerce/SimplCommerce pull request #1079
Opened 2024-01-10 06:37 UTC by Arunkumar0610

added tests for  #1037 #1069 
 **SimplCommerce.Module.ProductComparison
Services - ComparingProductService
Controllers - ComparingProductController**

2024-01-10 20:44 UTC, hishamco requested changes

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +        #region PositiveTestCases
Please remove the region

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion

            // Act
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion

            // Assert
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion

            // Act
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion

            // Assert
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion

            // Act
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion

            // Assert
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion

            // Act
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion

            // Assert
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion

            // Act
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion

            // Assert
```

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/SimplCommerce.Module.ProductComparison.Tests.csproj
> +      <Folder Include="Controllers\" />
Check if these are needed

2024-01-10 20:44 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Services/ComparingProductServiceTests.cs
> +        #region PositiveTestCases
Remove the region

2024-01-11 05:09 UTC, hishamco approved these changes

2024-01-11 05:09 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion

            // Assert
```

2024-01-11 05:09 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion
            // Act
```

2024-01-11 05:09 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +
```suggestion
```

2024-01-11 05:09 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion
            // Assert
```

2024-01-11 05:12 UTC, hishamco requested changes

2024-01-11 05:12 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion
            // Act
```

2024-01-11 05:12 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion
            // Assert
```

2024-01-11 05:12 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion
            // Act
```

2024-01-11 05:12 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion
            // Assert
```

2024-01-11 05:21 UTC, hishamco requested changes

2024-01-11 05:21 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Assert
```suggestion
            // Assert
```

2024-01-11 05:21 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +            // Act
```suggestion
            // Act
```

2024-01-11 05:21 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Services/ComparingProductServiceTests.cs
> +                };
```suggestion
            var comparingProducts = new List<ComparingProduct>()
            {
                new ComparingProduct { UserId = fromUserId, ProductId = 1001 },
                new ComparingProduct { UserId = fromUserId, ProductId = 1002 },
            };
```

2024-01-11 05:21 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Services/ComparingProductServiceTests.cs
> +        };
```suggestion
            var listComparingProducts = new List<ComparingProduct>()
            {
                new ComparingProduct()
                {
                    ProductId = 1001,
                    Product=new Product()
                    {
                        Name="TestProduct"
                    },
                    CreatedOn = DateTime.Now,
                    UserId=1
                },
                new ComparingProduct()
                {
                    ProductId = 1002,
                    Product=new Product()
                    {
                        Name="TestProduct1"
                    },
                    CreatedOn = DateTime.Now,
                    UserId=1
                },
                new ComparingProduct()
                {
                    ProductId = 1003,
                    Product=new Product()
                    {
                        Name="TestProduct2"
                    },
                    CreatedOn = DateTime.Now,
                    UserId=1
                },
                new ComparingProduct()
                {
                    ProductId = 1004,
                    Product=new Product()
                    {
                        Name="TestProduct3"
                    },
                    CreatedOn = DateTime.Now,
                    UserId=1
                },
            };
```

2024-01-11 06:21 UTC, hishamco requested changes

2024-01-11 06:21 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Controllers/ComparingProductControllerTests.cs
> +namespace SimplCommerce.Module.ProductComparison.Tests.Controllers
```suggestion

namespace SimplCommerce.Module.ProductComparison.Tests.Controllers
```

2024-01-11 06:21 UTC, hishamco commented on test/SimplCommerce.Module.ProductComparison.Tests/Services/ComparingProductServiceTests.cs
> +namespace SimplCommerce.Module.ProductComparison.Tests.Services
```suggestion

namespace SimplCommerce.Module.ProductComparison.Tests.Services
```

2024-01-11 09:07 UTC, Arunkumar0610 commented
@hishamco Yes I ran the tests at my end everything works as excepted

2024-01-11 10:37 UTC, hishamco commented
Please resolve the conflict

2024-01-11 13:01 UTC, Arunkumar0610 commented
@hishamco Resolved the conflict

2024-01-11 13:15 UTC, hishamco approved these changes

2024-01-11 13:15 UTC, merged