#1090: Notification to the consumer when the product is back in stock
simplcommerce/SimplCommerce pull request #1091
Opened 2024-03-09 14:19 UTC by s04v

#1090 Implementation

2024-03-10 13:56 UTC, hishamco requested changes

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Catalog/Areas/Catalog/Views/Product/ProductDetail.cshtml
> +                                @if (SignInManager.IsSignedIn(User))
```suggestion
                                @if (User.Identity.IsAuthenticated)
```

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Core/Extensions/WorkContext.cs
> +
```suggestion
        public string GetCurrentHostName() => _httpContext.Request.Host.Value;

```

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Inventory/Areas/Inventory/Controllers/StockApiController.cs
> +                .AnyAsync())
```suggestion
            if (await _backInStockSubscriptionRepository.Query()
                .AnyAsync(o => o.ProductId == productId && o.CustomerEmail == customerEmail))
```

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Inventory/Event/BackInStock.cs
> +    public class BackInStock : INotification
ProductBackInStock might more meaningful

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Inventory/Event/BackInStockSendEmailHandler.cs
> +        }
```suggestion
        public BackInStockSendEmailHandler(IStockSubscriptionService stockSubscriptionService)
            => _stockSubscriptionService = stockSubscriptionService;
```

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Inventory/Event/BackInStockSendEmailHandler.cs
> +        }
```suggestion
        public async Task Handle(BackInStock notification, CancellationToken cancellationToken)
            => await _stockSubscriptionService.BackInStockSendNotificationsAsync(notification.ProductId);
```

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Inventory/Models/BackInStockSubscription.cs
> +        public long ProductId { get; set; }
```suggestion
        public long ProductId { get; set; }

```

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Inventory/ModuleInitializer.cs
> +
```suggestion
```

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Inventory/Services/StockService.cs
> +
```suggestion
```

2024-03-10 13:56 UTC, hishamco commented on src/Modules/SimplCommerce.Module.Inventory/Services/StockSubscriptionService.cs
> +            await _backInStockSubscriptionRepository.SaveChangesAsync();
```suggestion

            await _backInStockSubscriptionRepository.SaveChangesAsync();
```

2024-03-10 15:19 UTC, merged

2024-03-10 21:55 UTC, hishamco commented
@thiennn I suggested some improvements to this PR also, there 're some non meaningful names, but seems you ignored all the my code suggestions

2024-03-10 22:41 UTC, s04v commented
@hishamco I can make your improvements in the new PR

2024-03-10 22:48 UTC, hishamco commented
Believe it or not, it doesn't require a new PR, that's why the reviewing is helpful otherwise it's a waste of time if no one consider it

Don't get me wrong

2024-03-11 02:19 UTC, thiennn commented
Hi @hishamco , I am sorry. I was on a mobile and I didn't see your suggestion.

@s04v Yes, please help me make the new PR, Thanks